### ISSUE TITLE
PDF download option doesn't work for all icons

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#48] opened 2021-02-22 14:48 UTC
### Kind of issue 

- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Some PDF download options do not work. This is due to the fact that [simple-icons-pdf](https://github.com/simple-icons/simple-icons-pdf) is behind on [simple-icons](https://github.com/simple-icons/simple-icons) because the [converter bot](https://github.com/simple-icons/svg-to-pdf-bot) is no longer functional.

Until we are aware of demand for PDF versions of the logos, we consider this bug to be low priority.

**Comment by adamrusted** [comment] 2021-05-28 16:43
The resolution for this _should_ come after https://github.com/simple-icons/simple-icons-pdf/pull/1 is merged.
We'll need to look at some GH Actions work to make it sync up to the main repo, much like this one does - but should be achievable without too much work.

**Comment by jorgeamadosoria** [comment] 2021-09-07 18:00
@ericcornelissen @adamrusted if the root cause is already determined to be that some PDFs are not being generated, then wouldn't this be a bug in the PDF repo and not in the website?
Because judging by the description, there is really nothing that can be done to fix this in the website code, is there?

**Comment by ericcornelissen** [comment] 2021-09-07 18:29
I think it's still useful to have a bug for upstream issues. If you want to clarify, we can introduce an `upstream` label. Or close it if you prefer.

**Comment by jorgeamadosoria** [comment] 2021-09-07 19:05
I added an "out of scope" label. I know it's not the best fitting one, but until we get the upstream one going, I think it marks the issue just fine. 
I would prefer closing it and opening a new one for the PDF repository. But I don't know how visible that's going to be.

**Comment by jorgeamadosoria** [comment] 2021-10-17 15:56
Due to lack of any other activity in this (and since we already established that this is not a website issue), I'm closing this ticket.

**Closed as completed by jorgeamadosoria** 2021-10-17 15:56 UTC
Labels: bug, out of scope
